site_name: Dokumentasi JavaScript dari Nol
site_url: https://Delta_Code26.github.io/dokumentasi-javascript-dari-nol
repo_url: https://github.com/Delta-Code26/dokumentasi-javascript-dari-nol.git
theme:
  name: 'material'  # Kamu bisa memilih tema lainnya juga
  language: 'id'
nav:
  - Home: index.md
  - Pemula:
      - Intro: javascript/01-pemula/intro.md
      - Variabel: javascript/01-pemula/variabel.md
      - Tipe Data: javascript/01-pemula/tipe-data.md
      - Operator: javascript/01-pemula/operator.md
      - Control Flow: javascript/01-pemula/control-flow.md
      - Array & Object: javascript/01-pemula/array-object.md
      - Fungsi: javascript/01-pemula/fungsi.md
  - Menengah:
      - Struktur Data: javascript/02-menengah/struktur-data.md
      - Higher-Order Functions: javascript/02-menengah/higher-order.md
      - ASYNC: javascript/02-menengah/async.md
      - Modularisasi: javascript/02-menengah/modularisasi.md
      - DOM EVENT: javascript/02-menengah/dom-event.md
      - FETCH API: javascript/02-menengah/fetch-api.md
  - Mahir:
      - Konsep Lanjutan: javascript/03-mahir/konsep-lanjut.md
      - OOP: javascript/03-mahir/oop.md
      - Functional Programming: javascript/03-mahir/functional.md
      - Event Loop: javascript/03-mahir/event-loop.md
      - Tools: javascript/03-mahir/tools.md
      - Keamanan: javascript/03-mahir/keamanan.md
  - Best Practices:
      - Clean Code: javascript/04-best-practices/clean-code.md
      - Debugging: javascript/04-best-practices/debugging.md
      - Komentar: javascript/04-best-practices/komentar.md
      - Refactor: javascript/04-best-practices/refactor.md
      - Style Guide: javascript/04-best-practices/style-guide.md
      - Testing: javascript/04-best-practices/testing.md
      - error-handling: javascript/04-best-practices/error-handling.md
      - Performance: javascript/04-best-practices/performance.md
      - Eslintcr & Prettier: javascript/04-best-practices/eslintrc-prettierrc.md

      
repo_url: https://github.com/Delta-Code26/dokumentasi-javascript-dari-nol
edit_uri: main/docs/
