site_name: Dokumentasi JavaScript dari Nol
site_url: https://Delta_Code26.github.io/dokumentasi-javascript-dari-nol
repo_url: https://github.com/Delta-Code26/dokumentasi-javascript-dari-nol.git
edit_uri: edit/main/docs/
theme:
  name: 'material'
  language: 'id'
  features:
    - navigation.tabs
    - navigation.sections
  icon:
    repo: fontawesome/brands/github
  nav_icons:
    - home: material/home
    - JavaScript: simple/javascript
    - PYTHON: simple/python
    - JAVA: simple/java


nav:
  - Home: index.md
  - JavaScript:
      - Pemula:
          - Intro: javascript/01-intro.md
          - Variabel: javascript/02-variabel.md
          - Tipe Data: javascript/03-tipe-data.md
          - Operator: javascript/04-operator.md
          - Control Flow: javascript/05-control-flow.md
          - Array & Object: javascript/06-array-object.md
          - Fungsi: javascript/07-fungsi.md
      - Menengah:
          - Struktur Data: javascript/08-struktur-data.md
          - Higher-Order Functions: javascript/09-higher-order.md
          - ASYNC: javascript/10-async.md
          - Modularisasi: javascript/11-modularisasi.md
          - DOM EVENT: javascript/12-dom-event.md
          - FETCH API: javascript/13-fetch-api.md
      - Mahir:
          - Konsep Lanjutan: javascript/14-konsep-lanjut.md
          - OOP: javascript/15-oop.md
          - Functional Programming: javascript/16-functional.md
          - Event Loop: javascript/17-event-loop.md
          - Tools: javascript/18-tools.md
          - Keamanan: javascript/19-keamanan.md
      - Best Practices:
          - Clean Code: javascript/20-clean-code.md
          - Debugging: javascript/21-debugging.md
          - Komentar: javascript/22-komentar.md
          - Refactor: javascript/23-refactor.md
          - Style Guide: javascript/24-style-guide.md
          - Testing: javascript/25-testing.md
          - error-handling: javascript/26-error-handling.md
          - Performance: javascript/27-performance.md
          - Eslintcr & Prettier: javascript/28-eslintrc-prettierrc.md
  - PYTHON:
    - Pemula:
      - Intro: python/01-intro.md
      - Variabel: python/02-variabel.md
      - Tipe Data: python/03-tipe-data.md
      - Operator: python/04-operator.md
      - Control Flow: python/05-control-flow.md
      - Array & Object: python/06-array-object.md
      - Fungsi: python/07-fungsi.md
    - Menengah:
      - Struktur Data: python/08-struktur-data.md
      - Higher-Order Functions: python/09-higher-order.md
      - ASYNC: python/10-async.md
      - Modularisasi: python/11-modularisasi.md
      - DOM EVENT: python/12-dom-event.md
      - FETCH API: python/13-fetch-api.md
    - Mahir:
      - Konsep Lanjutan: python/14-konsep-lanjut.md
      - OOP: python/15-oop.md
      - Functional Programming: python/16-functional.md
      - Event Loop: python/17-event-loop.md
      - Tools: python/18-tools.md
      - Keamanan: python/19-keamanan.md
    - Best Practices:
      - Clean Code: python/20-clean-code.md 
      - Debugging: python/21-debugging.md
      - Komentar: python/22-komentar.md
      - Refactor: python/23-refactor.md
      - Style Guide: python/24-style-guide.md
      - Testing: python/25-testing.md
      - error-handling: python/26-error-handling.md
      - Performance: python/27-performance.md
      - Eslintcr & Prettier: python/28-eslintrc-prettierrc.md
  - JAVA:
    - Pengenalan: belajar-java/01-Pengenalan-Java.md
    - Instalasi dan Setup: belajar-java/02-Instalasi-dan-Setup-Java.md
    - Program Pertama di Java: belajar-java/03-Program-Pertama-di-Java.md
    - Struktur Dasar Program Java: belajar-java/04-Struktur-Dasar-Program-Java.md
    - Tipe Data dan Variabel: belajar-java/05-Tipe-Data-dan-Variabel.md
    - Operator di Java: belajar-java/06-Operator-di-Java.md
    - Percabangan if, switch: belajar-java/07-Percabangan-if,-switch.md
    - Perulangan for, while, do-while: belajar-java/08-Perulangan-for,-while,-do-while.md
    - Array di Java: belajar-java/09-Array-di-Java.md
    - String dan Manipulasi String: belajar-java/10-String-dan-Manipulasi-String.md
    - Konsep OOP di Java: belajar-java/11-Konsep-OOP-di-Java.md
    - Class dan Object: belajar-java/12-Class-dan-Object.md
    - Package dan Import: belajar-java/13-Package-dan-Import.md
    - Constructor dan Overloading: belajar-java/14-Constructor-dan-Overloading.md
    - Inheritance Pewarisan: belajar-java/15-Inheritance-Pewarisan.md
    - Polymorphism: belajar-java/16-Polymorphism.md
    - Encapsulation: belajar-java/17-Encapsulation.md
    - Abstraksi dan Interface: belajar-java/18-Abstraksi-dan-Interface.md
    - This dan Super Keyword: belajar-java/19-This-dan-Super-Keyword.md
    - Access Modifiers: belajar-java/20-Access-Modifiers.md
    - Static vs Non-Static: belajar-java/21-Static-vs-Non-Static.md
    - Final Keyword dan Konstanta: belajar-java/22-Final-Keyword-dan-Konstanta.md
    - ArrayList, LinkedList, HashSet, TreeSet: belajar-java/23-ArrayList,-LinkedList,-HashSet,-TreeSet.md
    - HashMap, TreeMap: belajar-java/24-HashMap,-TreeMap.md
    - Iterator dan For Each: belajar-java/25-Iterator-dan-For-Each.md
    - Generic di Java: belajar-java/26-Generic-di-Java.md
    - Try, Catch, Finally: belajar-java/27-Try,-Catch,-Finally.md
    - Multiple Catch dan Nested Try: belajar-java/28-Multiple-Catch-dan-Nested-Try.md
    - Throw dan Throws: belajar-java/29-Throw-dan-Throws.md
    - Custom Exception: belajar-java/30-Custom-Exception.md
    - Scanner dan BufferedReader: belajar-java/31-Scanner-dan-BufferedReader.md
    - Menulis dan Membaca File: belajar-java/32-Menulis-dan-Membaca-File.md
    - Serialization dan Deserialization: belajar-java/33-Serialization-dan-Deserialization.md
    - Thread Class dan Runnable Interface: belajar-java/34-Thread-Class-dan-Runnable-Interface.md
    - Synchronized dan Lock: belajar-java/35-Synchronized-dan-Lock.md
    - Thread Pool dan ExecutorService: belajar-java/36-Thread-Pool-dan-ExecutorService.md
    - Deadlock dan Race Condition: belajar-java/37-Deadlock-dan-Race-Condition.md
    - Pengenalan Networking di Java: belajar-java/38-Pengenalan-Networking-di-Java.md
    - Socket Programming: belajar-java/39-Socket-Programming.md
    - Membuat Client Server Sederhana: belajar-java/40-Membuat-Client-Server-Sederhana.md
    - HTTP Request dengan Java: belajar-java/41-HTTP-Request-dengan-Java.md
    - Debugging di IDE: belajar-java/42-Debugging-di-IDE.md
    - Unit Testing dengan JUnit: belajar-java/43-Unit-Testing-dengan-JUnit.md
    - Logging dan Error Handling Best Practices: belajar-java/44-Logging-dan-Error-Handling-Best-Practices.md
    - Profiling dan Performance Optimization: belajar-java/45-Profiling-dan-Performance-Optimization.md
    - Pengenalan Swing dan AWT: belajar-java/46-Pengenalan-Swing-dan-AWT.md
    - Membuat Frame dan Layout: belajar-java/47-Membuat-Frame-dan-Layout.md
    - Button, TextField, Label, dll: belajar-java/48-Button,-TextField,-Label,-dll.md
    - Event Handling: belajar-java/49-Event-Handling.md
    - Proyek GUI Sederhana: belajar-java/50-Proyek-GUI-Sederhana.md
    - Apa itu Android dan Hubungannya dengan Java: belajar-java/51-Apa-itu-Android-dan-Hubungannya-dengan-Java.md
    - Struktur Proyek Android Studio: belajar-java/52-Struktur-Proyek-Android-Studio.md
    - Activity dan Layout: belajar-java/53-Activity-dan-Layout.md
    - Java untuk Android Development: belajar-java/54-Java-untuk-Android-Development.md
    - Membuat Aplikasi Kalkulator: belajar-java/55-Membuat-Aplikasi-Kalkulator.md
    - Aplikasi Manajemen Data Mahasiswa: belajar-java/56-Aplikasi-Manajemen-Data-Mahasiswa.md
    - To Do List dengan GUI: belajar-java/57-To-Do-List-dengan-GUI.md
    - Mini CRUD dengan File: belajar-java/58-Mini-CRUD-dengan-File.md
    - Sistem Login Sederhana: belajar-java/59-Sistem-Login-Sederhana.md
    - Java Design Patterns Factory, Singleton, dll: belajar-java/60-Java-Design-Patterns-Factory,-Singleton,-dll.md
    - Clean Code dengan Java: belajar-java/61-Clean-Code-dengan-Java.md
    - Refactoring dan Maintainability: belajar-java/62-Refactoring-dan-Maintainability.md
    - Style Guide dan Konvensi Penamaan: belajar-java/63-Style-Guide-dan-Konvensi-Penamaan.md
    - Maven dan Gradle untuk Manajemen Proyek: belajar-java/64-Maven-dan-Gradle-untuk-Manajemen-Proyek.md
    - Java 8 Features Lambda, Stream API: belajar-java/65-Java-8-Features-Lambda,-Stream-API.md
    - Java 17 dan Versi Terbaru Record, Sealed Classes, dll: belajar-java/66-Java-17-dan-Versi-Terbaru-Record,-Sealed-Classes,-dll.md
    - Secure Coding dan SQL Injection: belajar-java/67-Secure-Coding-dan-SQL-Injection.md
    - JDBC dan Koneksi Database: belajar-java/68-JDBC-dan-Koneksi-Database.md
    - index: belajar-java/index.md
repo_url: https://github.com/Delta-Code26/dokumentasi-javascript-dari-nol
edit_uri: main/docs/
